# Generated by Django 4.2.11 on 2024-03-29 10:00
from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def create_group_and_permission(apps, schema_editor):
    # Get the Recipe model
    recipe = apps.get_model('recipes_app', 'Recipe')

    # Create a group
    group, created = Group.objects.get_or_create(name='Moderators')

    # Create a custom permission
    content_type = ContentType.objects.get_for_model(recipe)
    permission, created = Permission.objects.get_or_create(
        codename='can_change_recipe',
        name='Can change recipe',
        content_type=content_type,
    )

    # Assign the permission to the group
    if created:
        group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group_and_permission),
    ]
