# Generated by Django 4.2.11 on 2024-04-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_recipeimage_recipe_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.recipe'),
        ),
    ]
